"""
SAHAAYA demo API (Vercel serverless).

Serves a snapshot of REAL model output. snapshot.json is generated by running the
actual pipeline in services/api-gateway - DistressEngine, ExplainabilityEngine and
the lightweight emotion classifier over the synthetic dataset - and capturing the
responses. Regenerate it with scripts/build_snapshot.py whenever the engine or the
dataset changes.

Why a snapshot rather than live inference: the real stack (scikit-learn, pandas,
scipy and xgboost, which is required because the saved classifier is an
XGBClassifier) bundles to 618 MB against Vercel's hard 500 MB function limit. The
Docker/Render configuration in render.yaml runs the same code live and is the route
to real-time scoring.

This replaces an earlier stub that derived scores arithmetically from the victim ID
(`25 + ((number * 17) % 70)`) and returned text_emotion, behavioural, voice,
case_events and trend hardcoded to 0, which is why only Self Report ever appeared in
the officer report. Every number served here is genuine engine output.

Writes (check-ins, support requests, review decisions) are accepted and held in
memory for the life of the instance so the demo flows work end to end; they do not
re-run scoring.
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional
import json
import re
import uuid

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

app = FastAPI(title="SAHAAYA API", version="1.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://sih-sahaaya.vercel.app", "http://localhost:3000", "http://127.0.0.1:3000"],
    allow_origin_regex=r"https://sih-sahaaya-[a-z0-9-]+-achinth52200s-projects\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SNAPSHOT: Dict[str, Any] = json.loads((Path(__file__).parent / "snapshot.json").read_text(encoding="utf-8"))

# Runtime-only state; resets when the instance recycles.
checkins: List[Dict[str, Any]] = []
support_requests: List[Dict[str, Any]] = []
review_actions: Dict[str, List[Dict[str, Any]]] = {}
alert_overrides: Dict[str, Dict[str, Any]] = {}


def _victim_ids() -> List[str]:
    return [v["victim_id"] for v in SNAPSHOT["victims"]]


def _require(section: str, victim_id: str) -> Dict[str, Any]:
    data = SNAPSHOT[section].get(victim_id)
    if data is None:
        raise HTTPException(status_code=404, detail="Victim not found")
    return data


class LoginRequest(BaseModel):
    email: str
    password: str


class CheckInRequest(BaseModel):
    victim_id: str = "VICTIM_0001"
    scores: Optional[Dict[str, float]] = None
    message: Optional[str] = None


class SupportRequestBody(BaseModel):
    victim_id: str = "VICTIM_0001"
    request_type: Optional[str] = None
    message: Optional[str] = Field(default="", max_length=2000)


class ReviewBody(BaseModel):
    actor_id: str
    actor_role: str
    decision: str
    notes: str = ""
    review_duration_seconds: Optional[int] = None


@app.get("/health")
def health() -> Dict[str, Any]:
    return {
        "status": "healthy",
        "version": "1.0.0",
        "models_loaded": True,
        "data_loaded": True,
        "mode": "snapshot of real engine output",
    }


@app.post("/auth/login")
def login(request: LoginRequest) -> Dict[str, Any]:
    roles = {
        "victim@sahaaya.gov.in": "victim",
        "counsellor@sahaaya.gov.in": "counsellor",
        "district@sahaaya.gov.in": "district_officer",
        "state@sahaaya.gov.in": "state_officer",
        "national@sahaaya.gov.in": "national_admin",
    }
    email = request.email.lower()
    role = roles.get(email)
    number = 1
    victim_match = re.fullmatch(r"victim(\d*)@sahaaya\.gov\.in", email)
    if victim_match:
        number = int(victim_match.group(1) or "1")
        if 1 <= number <= 25:
            role = "victim"
    if not role or request.password != "demo123":
        raise HTTPException(status_code=401, detail="Invalid demo credentials")
    return {
        "access_token": f"demo-{uuid.uuid4()}",
        "refresh_token": f"demo-refresh-{uuid.uuid4()}",
        "user": {
            "id": f"VICTIM_{number:04d}" if role == "victim" else request.email,
            "email": request.email,
            "role": role,
        },
    }


# ===== Victims =====

@app.get("/api/v1/victims")
def victims() -> List[Dict[str, Any]]:
    return SNAPSHOT["victims"]


@app.get("/api/v1/victims/{victim_id}")
def victim_detail(victim_id: str) -> Dict[str, Any]:
    detail = json.loads(json.dumps(_require("detail", victim_id)))
    extra = [c for c in checkins if c.get("victim_id") == victim_id]
    if extra:
        detail.setdefault("history", {}).setdefault("checkins", []).extend(extra)
    return detail


@app.get("/api/v1/victims/{victim_id}/distress")
def distress(victim_id: str) -> Dict[str, Any]:
    return _require("distress", victim_id)


@app.get("/api/v1/victims/{victim_id}/distress/history")
def distress_history(victim_id: str) -> List[Dict[str, Any]]:
    return _require("history", victim_id)


@app.get("/api/v1/victims/{victim_id}/explanation")
def explanation(victim_id: str) -> Dict[str, Any]:
    return _require("explanation", victim_id)


# ===== Review workflow =====

def _alerts() -> List[Dict[str, Any]]:
    return [alert_overrides.get(a["alert_id"], a) for a in SNAPSHOT["alerts"]]


@app.get("/api/v1/review/alerts")
def review_alerts(
    status: Optional[str] = None,
    priority: Optional[str] = None,
    victim_id: Optional[str] = None,
    limit: int = 200,
) -> List[Dict[str, Any]]:
    result = _alerts()
    if status:
        result = [a for a in result if a.get("status") == status]
    if priority:
        result = [a for a in result if a.get("priority") == priority]
    if victim_id:
        result = [a for a in result if a.get("victim_id") == victim_id]
    return result[:limit]


@app.get("/api/v1/review/alerts/{alert_id}")
def review_alert(alert_id: str) -> Dict[str, Any]:
    for alert in _alerts():
        if alert["alert_id"] == alert_id:
            return alert
    raise HTTPException(status_code=404, detail="Alert not found")


@app.get("/api/v1/review/alerts/{alert_id}/history")
def alert_history(alert_id: str) -> List[Dict[str, Any]]:
    return review_actions.get(alert_id, [])


@app.get("/api/v1/review/alerts/{alert_id}/interventions")
@app.get("/api/v1/review/interventions")
def interventions(alert_id: Optional[str] = None, victim_id: Optional[str] = None) -> List[Dict[str, Any]]:
    return []


@app.post("/api/v1/review/alerts/{alert_id}/review")
def submit_review(alert_id: str, body: ReviewBody) -> Dict[str, Any]:
    alert = json.loads(json.dumps(review_alert(alert_id)))
    status_for = {
        "dismiss": "false_positive",
        "escalate": "escalated",
        "confirm_intervene": "intervention_decided",
        "confirm_monitor": "intervention_decided",
        "request_more_info": "in_review",
    }
    alert["status"] = status_for.get(body.decision, "in_review")
    alert["reviewed_by"] = body.actor_id
    alert["review_decision"] = body.decision
    alert["updated_at"] = datetime.now(timezone.utc).isoformat()
    alert_overrides[alert_id] = alert

    review_actions.setdefault(alert_id, []).append({
        "action_id": f"ACT_{uuid.uuid4().hex[:12].upper()}",
        "alert_id": alert_id,
        "actor_id": body.actor_id,
        "actor_role": body.actor_role,
        "action": body.decision,
        "notes": body.notes,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })
    return alert


@app.post("/api/v1/review/alerts/generate")
def generate_alerts() -> Dict[str, Any]:
    return {"generated": len(SNAPSHOT["alerts"]),
            "alerts": [{"alert_id": a["alert_id"], "victim_id": a["victim_id"], "band": a["band"]}
                       for a in SNAPSHOT["alerts"]]}


@app.get("/api/v1/review/stats/summary")
def review_summary() -> Dict[str, Any]:
    return SNAPSHOT["review_summary"]


# ===== Dashboards =====

@app.get("/api/v1/dashboard/national")
def national() -> Dict[str, Any]:
    return SNAPSHOT["national"]


@app.get("/api/v1/dashboard/district/{district_id}")
def district(district_id: str) -> Dict[str, Any]:
    members = [v for v in SNAPSHOT["victims"] if v.get("district") == district_id]
    bands = {"Green": 0, "Yellow": 0, "Orange": 0, "Red": 0}
    for v in members:
        if v.get("latest_band") in bands:
            bands[v["latest_band"]] += 1
    return {
        "district": district_id,
        "total_victims": len(members),
        "band_distribution": bands,
        "high_risk_count": bands["Orange"] + bands["Red"],
        "victims": [{"victim_id": v["victim_id"], "case_type": v["case_type"],
                     "score": v.get("latest_score"), "band": v.get("latest_band"),
                     "trend": v.get("trend"),
                     "escalation_7d": v.get("escalation_probability_7d")} for v in members],
    }


@app.get("/api/v1/dashboard/state/{state_id}")
def state(state_id: str) -> Dict[str, Any]:
    members = [v for v in SNAPSHOT["victims"] if v.get("state") == state_id]
    bands = {"Green": 0, "Yellow": 0, "Orange": 0, "Red": 0}
    for v in members:
        if v.get("latest_band") in bands:
            bands[v["latest_band"]] += 1
    districts: Dict[str, Dict[str, Any]] = {}
    for v in members:
        d = districts.setdefault(v["district"], {
            "district": v["district"], "total_victims": 0,
            "band_distribution": {"Green": 0, "Yellow": 0, "Orange": 0, "Red": 0},
            "high_risk_count": 0})
        d["total_victims"] += 1
        if v.get("latest_band") in d["band_distribution"]:
            d["band_distribution"][v["latest_band"]] += 1
        d["high_risk_count"] = d["band_distribution"]["Orange"] + d["band_distribution"]["Red"]
    high = bands["Orange"] + bands["Red"]
    return {
        "state": state_id,
        "total_victims": len(members),
        "total_districts": len(districts),
        "band_distribution": bands,
        "high_risk_count": high,
        "high_risk_percentage": round(high / len(members) * 100) if members else 0,
        "districts": list(districts.values()),
    }


# ===== Victim-facing writes =====

@app.post("/api/v1/checkins")
def submit_checkin(body: CheckInRequest) -> Dict[str, Any]:
    scores = body.scores or {}
    urgent = float(scores.get("safety", 50)) <= 15 or float(scores.get("urgent_help", 0)) == 1
    record = {
        "checkin_id": str(uuid.uuid4()),
        "victim_id": body.victim_id,
        "checkin_date": datetime.now(timezone.utc).isoformat(),
        "scores": scores,
        "message": body.message,
        "channel": "web",
        "label": "[PROTOTYPE DATA - NOT REAL VICTIM DATA]",
    }
    checkins.append(record)
    routed = ["counsellor", "district_officer"] if urgent else []
    return {"status": "recorded", "checkin": record, "human_review": bool(routed), "routed_roles": routed}


@app.post("/api/v1/support-requests")
def create_support_request(body: SupportRequestBody) -> Dict[str, Any]:
    routed = ["counsellor", "district_officer"] if body.request_type == "urgent_safety" else ["counsellor"]
    record = {
        "request_id": str(uuid.uuid4()),
        "victim_id": body.victim_id,
        "request_type": body.request_type or "counselling",
        "message": body.message,
        "routed_roles": routed,
        "status": "open",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    support_requests.append(record)
    return record


@app.get("/api/v1/support-requests")
def list_support_requests(role: Optional[str] = None, since: Optional[str] = None) -> List[Dict[str, Any]]:
    if role:
        return [r for r in support_requests if role in r.get("routed_roles", [])]
    return support_requests
